name : "My first workflow"

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: "Just say hello"
          run: echo "Branch is ${{ github.ref_name }}"
    second_job:
        needs: first_job
        if: github.ref_name == 'main'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                commands: ['pwd', 'uptime', 'df']
        steps:
        - run: ${{ matrix.commands }}